# Generated by Django 3.2.3 on 2022-07-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_hospital_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
